apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictactoe-app
  template:
    metadata:
      labels:
        app: tictactoe-app
    spec:
      containers:
      - name: tictactoe-app-container
        image: soravkumarsharma/gitops-tictactoe-app:34
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32000
  selector:
    app: tictactoe-app
